### PR TITLE
Avoid heap buffer overflow in valkeyAsyncFormattedCommand

### LINKED ISSUE #242: [BUG] Heap OOB read in valkeyAsyncAppendCmdLen when processing non-NUL-terminated formatted command buffer
(moving from https://github.com/valkey-io/valkey/issues/2647)

Hi, there is a heap OOB reachable via `valkeyAsyncFormattedCommand`.

For certain crafted commands, it will read beyond the user specified `len` of the provided buffer.

The following testcase reproduces the crash on `983d67e4`.

(found via automated fuzzing)

**testcase.cpp**

```cpp
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstring>
extern "C" {
#include "valkey/valkey.h"
}
extern "C" {
#include "valkey/async.h"
}
int main(){
    // Create an async context (no event loop attach needed to reach the bug)
    valkeyAsyncContext *ac = valkeyAsyncConnect("127.0.0.1", 6379);
    if (!ac) return 0;
    if (ac->err) return 0;

    // Minimal RESP PING command, length is exactly 14 bytes; no NUL terminator in the heap buffer
    const char kPing[] = "*1\r\n$4\r\nPING\r\n"; // 14 bytes
    size_t len = sizeof(kPing) - 1;                // 14
    char *buf = (char*)malloc(len);                // allocate exactly 'len'
    memcpy(buf, kPing, len);                       // no trailing NUL written

    // Triggers heap OOB read at async.c:934 (hasnext = (p[0] == '$'))
    (void)valkeyAsyncFormattedCommand(ac, (valkeyCallbackFn*)nullptr, (void*)nullptr, buf, len);
    return 0;
}
```

**crash report**
```json
{
  "Date": "2025-09-25T03:29:56.766306+00:00",
  "Uname": "Linux 8b7c15300365 5.15.0-140-generic #150-Ubuntu SMP Sat Apr 12 06:00:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux",
  "OS": "Ubuntu",
  "OSRelease": "22.04",
  "Architecture": "amd64",
  "ExecutablePath": "/tmp/tmpmafm4r91/reproducer",
  "ProcEnviron": [
    "PREFIX=/fuzz/install",
    "LIBAFL_EDGES_MAP_SIZE=800000",
    "PWD=/fuzz/workspace",
    "CXX=gf_libafl_cxx",
    "GRAPHFUZZ_USE_ASAN=1",
    "HOME=/root",
    "ASAN_OPTIONS=hard_rss_limit_mb=1024:detect_leaks=0",
    "TERM=xterm-256color",
    "SHLVL=1",
    "LD_LIBRARY_PATH=/fuzz/install/lib",
    "PATH=/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "CC=gf_libafl_cc",
    "DEBIAN_FRONTEND=noninteractive",
    "OLDPWD=/fuzz/src/deps/libvalkey",
    "_=/usr/local/bin/agfi"
  ],
  "ProcCmdline": "/tmp/tmpmafm4r91/reproducer",
  "Stdin": "",
  "ProcStatus": [],
  "ProcMaps": [],
  "ProcFiles": [],
  "NetworkConnections": [],
  "CrashSeverity": {
    "Type": "NOT_EXPLOITABLE",
    "ShortDescription": "heap-buffer-overflow(read)",
    "Description": "Heap buffer overflow",
    "Explanation": "The target reads data past the end, or before the beginning, of the intended heap buffer."
  },
  "Stacktrace": [
    "    #0 0x7ffff7f4cab2 in valkeyAsyncAppendCmdLen /fuzz/src/deps/libvalkey/src/async.c:934:16",
    "    #1 0x55555565b4ae in main /tmp/tmpmafm4r91/reproducer.cpp:24:11",
    "    #2 0x7ffff79ded8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16",
    "    #3 0x7ffff79dee3f in __libc_start_main csu/../csu/libc-start.c:392:3",
    "    #4 0x555555580304 in _start (/tmp/tmpmafm4r91/reproducer+0x2c304) (BuildId: 092b33e33fb9d11a3c483079acce3c03a5d65867)"
  ],
  "Registers": {},
  "Disassembly": [],
  "Package": "",
  "PackageVersion": "",
  "PackageArchitecture": "",
  "PackageDescription": "",
  "AsanReport": [
    "==156==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50200000009e at pc 0x7ffff7f4cab3 bp 0x7fffffffe990 sp 0x7fffffffe988",
    "READ of size 1 at 0x50200000009e thread T0",
    "    #0 0x7ffff7f4cab2 in valkeyAsyncAppendCmdLen /fuzz/src/deps/libvalkey/src/async.c:934:16",
    "    #1 0x55555565b4ae in main /tmp/tmpmafm4r91/reproducer.cpp:24:11",
    "    #2 0x7ffff79ded8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16",
    "    #3 0x7ffff79dee3f in __libc_start_main csu/../csu/libc-start.c:392:3",
    "    #4 0x555555580304 in _start (/tmp/tmpmafm4r91/reproducer+0x2c304) (BuildId: 092b33e33fb9d11a3c483079acce3c03a5d65867)",
    "",
    "0x50200000009e is located 0 bytes after 14-byte region [0x502000000090,0x50200000009e)",
    "allocated by thread T0 here:",
    "    #0 0x55555561c6ae in malloc (/tmp/tmpmafm4r91/reproducer+0xc86ae) (BuildId: 092b33e33fb9d11a3c483079acce3c03a5d65867)",
    "    #1 0x55555565b482 in main /tmp/tmpmafm4r91/reproducer.cpp:20:24",
    "",
    "SUMMARY: AddressSanitizer: heap-buffer-overflow /fuzz/src/deps/libvalkey/src/async.c:934:16 in valkeyAsyncAppendCmdLen",
    "Shadow bytes around the buggy address:",
    "  0x501ffffffe00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
    "  0x501ffffffe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
    "  0x501fffffff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
    "  0x501fffffff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
    "  0x502000000000: fa fa 04 fa fa fa 04 fa fa fa 00 02 fa fa 00 00",
    "=>0x502000000080: fa fa 00[06]fa fa fa fa fa fa fa fa fa fa fa fa",
    "  0x502000000100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa",
    "  0x502000000180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa",
    "  0x502000000200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa",
    "  0x502000000280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa",
    "  0x502000000300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa",
    "Shadow byte legend (one shadow byte represents 8 application bytes):",
    "  Addressable:           00",
    "  Partially addressable: 01 02 03 04 05 06 07",
    "  Heap left redzone:       fa",
    "  Freed heap region:       fd",
    "  Stack left redzone:      f1",
    "  Stack mid redzone:       f2",
    "  Stack right redzone:     f3",
    "  Stack after return:      f5",
    "  Stack use after scope:   f8",
    "  Global redzone:          f9",
    "  Global init order:       f6",
    "  Poisoned by user:        f7",
    "  Container overflow:      fc",
    "  Array cookie:            ac",
    "  Intra object redzone:    bb",
    "  ASan internal:           fe",
    "  Left alloca redzone:     ca",
    "  Right alloca redzone:    cb",
    "==156==ABORTING"
  ],
  "MsanReport": [],
  "UbsanReport": [],
  "LuaReport": [],
  "PythonReport": [],
  "GoReport": [],
  "JavaReport": [],
  "RustReport": [],
  "JsReport": [],
  "CSharpReport": [],
  "CrashLine": "/fuzz/src/deps/libvalkey/src/async.c:934:16",
  "Source": [
    "    930    ",
    "    931        /* Find out which command will be appended. */",
    "    932        p = nextArgument(cmd, &cstr, &clen);",
    "    933        assert(p != NULL);",
    "--->934        hasnext = (p[0] == '$');",
    "    935        pvariant = (tolower(cstr[0]) == 'p') ? 1 : 0;",
    "    936        svariant = valkeyIsShardedVariant(cstr);",
    "    937        hasprefix = svariant || pvariant;",
    "    938        cstr += hasprefix;",
    "    939        clen -= hasprefix;"
  ]
}
```

### PR DESCRIPTION
**Pull request by bjosv**
`valkeyAsyncFormattedCommand` now returns `VALKEY_ERR` instead of crashing when the command length, or content, is faulty.

Adds validation of the parsed length to make sure we don't read past the buffer end.
The internal `nextArgument` function now takes a new function argument, the buffer length, to be able to do the validation.
        
Fixes #242

### CODE REVIEW

**Comment by bjosv** [comment]
Ups, found an issue, will fix

File: src/async.c [hunk 1]
```diff
@@ -808,21 +809,51 @@ void valkeyAsyncHandleTimeout(valkeyAsyncContext *ac) {
...
+ * The found string is returned by pointer via `str` and length in `strlen`. */
+static const char *nextArgument(const char *buf, size_t buflen, const char **str, size_t *strlen) {
+    const char *p = buf;
+    const size_t minlen = 7; /* '$1\r\n \r\n'*/
+    if (buf == NULL || buflen < minlen)
+        goto error;
+
+    /* Find a bulkstring identifier. */
     if (p[0] != '$') {
         p = strchr(p, '$');
```
[the remark this answers is not in the document]
Comment (michael-grunder) [reply src/async.c:825]: I think we can use `memchr` here? 

https://github.com/valkey-io/libvalkey/blob/15974930d7a43d6fdf9146b932b5432f448416c1/src/read.c#L149

File: src/async.c [hunk 2]
```diff
@@ -808,21 +809,51 @@ void valkeyAsyncHandleTimeout(valkeyAsyncContext *ac) {
...
-static const char *nextArgument(const char *start, const char **str, size_t *len) {
-    const char *p = start;
+/* Find the next argument in a command buffer, i.e. find the next bulkstring
+ * in an array of bulkstrings.
+ * Returns a pointer to the end of a found argument, which can be used when
+ * finding following arguments, or NULL when an argument is not found.
+ * The found string is returned by pointer via `str` and length in `strlen`. */
+static const char *nextArgument(const char *buf, size_t buflen, const char **str, size_t *strlen) {
+    const char *p = buf;
+    const size_t minlen = 7; /* '$1\r\n \r\n'*/
```
Comment (michael-grunder) [inline src/async.c:819]: Are we sure it can't be zero here?

```suggestion
    const size_t minlen = 6; /* '$0\r\n\r\n'*/
```

File: src/async.c [hunk 3]
```diff
@@ -808,21 +809,51 @@ void valkeyAsyncHandleTimeout(valkeyAsyncContext *ac) {
...
+        /* Fail if not found, or if buffer can't contain a complete bulkstring. */
+        if (p == NULL || (buflen - (p - buf)) < minlen)
+            goto error;
     }
+    p++; /* Skip found '$' */
+
+    /* Get length and next separator, fail if negative value or empty string. */
+    long int len;
+    char *sep;
+    if ((len = strtol(p, &sep, 10)) < 1)
```
Comment (michael-grunder) [inline src/async.c:835]: I assume this check means we never expect to parse null bulks (e.g. `$-1\r\n`).

File: tests/client_test.c [hunk 4]
```diff
@@ -1884,6 +1884,54 @@ void null_cb(valkeyAsyncContext *ac, void *r, void *privdata) {
...
+    valkeyAsyncContext *ac = valkeyAsyncConnectWithOptions(&options);
+    assert(ac);
+
+    /* Null ptr. */
+    assert(VALKEY_ERR == valkeyAsyncFormattedCommand(ac, NULL, NULL, NULL, 45));
+    /* Empty command. */
+    assert(VALKEY_ERR == valkeyAsyncFormattedCommand(ac, NULL, NULL, "", 0));
+    assert(VALKEY_ERR == valkeyAsyncFormattedCommand(ac, NULL, NULL, "  $", 2));
+    assert(VALKEY_ERR == valkeyAsyncFormattedCommand(ac, NULL, NULL, "*0\r\n", 4));
+    assert(VALKEY_ERR == valkeyAsyncFormattedCommand(ac, NULL, NULL, "*1\r\n$0\r\n\r\n", 10));
```
Comment (michael-grunder) [inline tests/client_test.c:1900]: This is valid RESP AFAIK

```printf '*1\r\n$0\r\n\r\n' |nc 127.0.0.1 6379```

File: src/async.c (hunk 2 above)
Comment (michael-grunder) [reply src/async.c:819]: Also this is personal preference but not all compilers will constant fold 

```c
const int minlen = 6
```

So a constant could be used instead:

```c
#define MIN_BULK_LEN ((size_t)6)
```

File: src/async.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (bjosv) [reply src/async.c:825]: Ah! Great idea, lets go with that instead.
Maybe I should run some benchmark when done, all these changes are run on each send command..

File: src/async.c (hunk 2 above)
Comment (bjosv) [reply src/async.c]: I removed the check now, using memchr and the length parser made it much easier

**Comment by bjosv** [comment]
I incorporated your length parser now so the PR got a bit bigger, but I think its more straight on.
I'll see if I can run some benchmark comparisons.
